/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  classifyFile: () => classifyFile,
  default: () => InkwellPlugin,
  extOf: () => extOf
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/InkwellView.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var RENDERABLE_EXTS = /* @__PURE__ */ new Set(["html", "htm", "md", "mdx", "yaml", "yml"]);
function extOf(name) {
  return name.includes(".") ? (name.split(".").pop() || "").toLowerCase() : "";
}
function classifyFile(ext) {
  const e = ext.toLowerCase();
  if (e === "html" || e === "htm") return "html";
  if (e === "md" || e === "mdx") return "md";
  if (e === "yaml" || e === "yml") return "yaml";
  return "other";
}

// src/vault.ts
var SKIP_DIRS = /* @__PURE__ */ new Set([
  "node_modules",
  ".git",
  ".next",
  ".nuxt",
  "dist",
  "build",
  "target",
  "__pycache__",
  ".cache",
  ".turbo",
  "vendor",
  ".obsidian",
  ".trash"
]);
async function listDirectory(adapter, dirPath) {
  const base = dirPath || "";
  let result;
  try {
    result = await adapter.list(base);
  } catch {
    return [];
  }
  const nodes = [];
  for (const folder of result.folders) {
    const name = folder.split("/").pop() || folder;
    if (name.startsWith(".")) continue;
    if (SKIP_DIRS.has(name.toLowerCase())) continue;
    nodes.push({ name, path: folder, isDir: true, ext: void 0, children: void 0 });
  }
  for (const file of result.files) {
    const name = file.split("/").pop() || file;
    if (name.startsWith(".")) continue;
    nodes.push({ name, path: file, isDir: false, ext: extOf(name), children: void 0 });
  }
  nodes.sort((a, b) => {
    if (a.isDir !== b.isDir) return a.isDir ? -1 : 1;
    return a.name.toLowerCase().localeCompare(b.name.toLowerCase());
  });
  return nodes;
}
async function readFileContent(adapter, filePath) {
  return adapter.read(filePath);
}
function collectRenderableFiles(vault, scope) {
  const all = vault.getFiles();
  return all.filter((f) => {
    if (scope && !f.path.startsWith(scope.endsWith("/") ? scope : scope + "/")) return false;
    return RENDERABLE_EXTS.has(extOf(f.name));
  });
}
async function findReferences(app, target, scope) {
  const { vault } = app;
  const baseName = target.name.replace(/\.[^.]+$/, "");
  const fullName = target.name;
  const candidates = collectRenderableFiles(vault, scope).filter(
    (f) => f.path !== target.path
  );
  const results = [];
  for (const file of candidates) {
    let content;
    try {
      content = await vault.cachedRead(file);
    } catch {
      continue;
    }
    if (!content) continue;
    const patterns = [
      new RegExp(`\\[\\[${escapeRegExp(baseName)}(?:\\|[^\\]]+)?\\]\\]`),
      new RegExp(`\\[\\[${escapeRegExp(fullName)}(?:\\|[^\\]]+)?\\]\\]`),
      new RegExp(`\\]\\([^)]*${escapeRegExp(target.path)}[^)]*\\)`),
      new RegExp(`\\]\\([^)]*${escapeRegExp(fullName)}[^)]*\\)`),
      new RegExp(`href=["'][^"']*${escapeRegExp(fullName)}[^"']*["']`)
    ];
    let hit = -1;
    let hitRaw = "";
    for (const re of patterns) {
      const m = re.exec(content);
      if (m) {
        hit = m.index;
        hitRaw = m[0];
        break;
      }
    }
    if (hit >= 0) {
      const start = Math.max(0, hit - 30);
      const end = Math.min(content.length, hit + hitRaw.length + 30);
      const context = content.substring(start, end).replace(/\n/g, " ").trim();
      results.push({
        name: file.name,
        path: file.path,
        context,
        ext: extOf(file.name)
      });
    }
  }
  return results;
}
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function folderOf(filePath) {
  const parts = filePath.split("/");
  return parts.length > 1 ? parts[parts.length - 2] : "";
}

// src/markdown.ts
function renderMarkdown(md) {
  let html = md;
  const MAX_FM_VAL_LEN = 80;
  const fmStore = [];
  html = html.replace(/^---\n([\s\S]*?)\n---\n*/g, (_m, fm) => {
    const lines = fm.trim().split("\n").filter(Boolean);
    if (lines.length === 0) return "\n\n";
    const items = lines.map((line) => {
      const idx = line.indexOf(":");
      if (idx === -1) return `<span class="fm-item fm-plain">${esc(line)}</span>`;
      const key = line.substring(0, idx).trim();
      let val = line.substring(idx + 1).trim();
      if (val.length > MAX_FM_VAL_LEN) {
        val = val.substring(0, MAX_FM_VAL_LEN) + "\u2026";
      }
      return `<span class="fm-item"><span class="fm-key">${esc(key)}</span><span class="fm-val">${esc(val)}</span></span>`;
    }).join("");
    const fmHtml = `<div class="frontmatter">${items}</div>`;
    const placeholder = `<div data-fm="${fmStore.length}"></div>`;
    fmStore.push(fmHtml);
    return placeholder + "\n\n";
  });
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_m, lang, code) => {
    const escaped = code.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    return `<pre><code class="lang-${lang}">${escaped}</code></pre>`;
  });
  html = html.replace(/([^\n])(\s*\d+\.\s+[\u4e00-\u9fa5A-Z])/g, "$1\n$2");
  html = textSplitBeforeBullets(html);
  html = html.replace(/`([^`\n]+)`/g, "<code>$1</code>");
  const lines3 = html.split("\n");
  html = lines3.map((line) => {
    if (/^###### /.test(line)) return line.replace(/^###### (.*)$/, "<h6>$1</h6>");
    if (/^##### /.test(line)) return line.replace(/^##### (.*)$/, "<h5>$1</h5>");
    if (/^#### /.test(line)) return line.replace(/^#### (.*)$/, "<h4>$1</h4>");
    if (/^### /.test(line)) return line.replace(/^### (.*)$/, "<h3>$1</h3>");
    if (/^## /.test(line)) return line.replace(/^## (.*)$/, "<h2>$1</h2>");
    if (/^# /.test(line)) return line.replace(/^# (.*)$/, "<h1>$1</h1>");
    return line;
  }).join("\n");
  const lines4 = html.split("\n");
  html = lines4.map((line) => {
    const m = line.match(/^(\d+)\.\s+([\u4e00-\u9fa5][^\n]*)$/);
    if (m && !line.match(/^[<]/)) {
      return `<h3 class="section-num">${m[1]}. ${m[2]}</h3>`;
    }
    return line;
  }).join("\n");
  const lines5 = html.split("\n");
  html = lines5.map((line) => {
    if (/^(---|\*\*\*|___)$/.test(line.trim()) && !line.startsWith("<")) return "<hr/>";
    return line;
  }).join("\n");
  html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" />');
  html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>');
  html = html.replace(/\*\*\*(.*?)\*\*\*/g, "<strong><em>$1</em></strong>");
  html = html.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(?!\*)(.*?)(?<!\*)\*/g, "<em>$1</em>");
  const lines6 = html.split("\n");
  html = lines6.map((line) => {
    if (/^>\s+/.test(line) && !line.startsWith("<")) {
      return line.replace(/^>\s+(.*)$/, "<blockquote>$1</blockquote>");
    }
    return line;
  }).join("\n");
  html = html.replace(/\[\[([^\]]+)\]\]/g, '<span class="wikilink">[[$1]]</span>');
  html = html.replace(/(^|\s)#([\u4e00-\u9fa5A-Za-z0-9_\/]+)/g, '$1<span class="tag">#$2</span>');
  const lines7 = html.split("\n");
  html = lines7.map((line) => {
    if (line.startsWith("<") || line.trim() === "") return line;
    const ulM = line.match(/^(\s*)([-*\u2022\u25e6\u25cb\u00b7])\s+(.*)$/);
    if (ulM) {
      const level = Math.floor(ulM[1].length / 2);
      const cls = level > 0 ? ` class="indent-${Math.min(level, 3)}"` : "";
      return `<li${cls}>${ulM[3]}</li>`;
    }
    const olM = line.match(/^(\s*)(\d+)\.\s+(.*)$/);
    if (olM && /^[\u4e00-\u9fa5]/.test(olM[3])) return line;
    if (olM) {
      const level = Math.floor(olM[1].length / 2);
      const cls = level > 0 ? ` class="indent-${Math.min(level, 3)}"` : "";
      return `<li class="ordered"${cls}>${olM[2]}. ${olM[3]}</li>`;
    }
    return line;
  }).join("\n");
  html = renderGFMTables(html);
  html = wrapListItems(html);
  html = wrapParagraphs(html);
  html = html.replace(/<div data-fm="(\d+)"><\/div>/g, (_m, idx) => fmStore[Number(idx)] || "");
  return html;
}
function renderGFMTables(text) {
  const lines = text.split("\n");
  const result = [];
  let tableLines = null;
  for (const rawLine of lines) {
    const line = rawLine;
    const isTableRow = /^\|(.+)\|$/.test(line.trim());
    const isSeparator = /^\|[\s\-:|\s]+\|$/.test(line.trim());
    if (isTableRow || isSeparator) {
      if (tableLines === null) {
        tableLines = [];
      }
      tableLines.push(line);
    } else {
      if (tableLines !== null) {
        result.push(buildGFMTable(tableLines));
        tableLines = null;
      }
      result.push(line);
    }
  }
  if (tableLines !== null) {
    result.push(buildGFMTable(tableLines));
  }
  return result.join("\n");
}
function buildGFMTable(lines) {
  const rows = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (/^[\s\-:|]+$/.test(trimmed.replace(/^\|/, "").replace(/\|$/, ""))) continue;
    const cells = trimmed.replace(/^\|/, "").replace(/\|$/, "").split("|").map((c) => c.trim());
    rows.push(cells);
  }
  if (rows.length === 0) return "";
  const numCols = Math.max(...rows.map((r) => r.length));
  let html = "<table>\n";
  for (let i = 0; i < rows.length; i++) {
    const tag = i === 0 ? "th" : "td";
    html += "  <tr>";
    for (let j = 0; j < numCols; j++) {
      const cell = rows[i][j] || "";
      html += `<${tag}>${cell}</${tag}>`;
    }
    html += "</tr>\n";
  }
  html += "</table>";
  return html;
}
function textSplitBeforeBullets(text) {
  return text.replace(/([^\n\s])(\s*)([\u2022\u25e6\u25cb\u00b7])(?=\s)/g, (_m, before, space, bullet) => `${before}
${space}${bullet}`).replace(/\n{2,}/g, "\n");
}
function wrapListItems(text) {
  const lines = text.split("\n");
  const result = [];
  let listBuf = null;
  let isOrderedBuf = false;
  for (const rawLine of lines) {
    const line = rawLine;
    const isLi = /^<li[\s>]/.test(line);
    const isOrdered = /class="ordered"/.test(line);
    if (isLi) {
      if (listBuf === null) {
        listBuf = [];
        isOrderedBuf = isOrdered;
        result.push(isOrdered ? "<ol>" : "<ul>");
      } else if (isOrdered !== isOrderedBuf) {
        result.push(isOrderedBuf ? "</ol>" : "</ul>");
        listBuf = [];
        isOrderedBuf = isOrdered;
        result.push(isOrdered ? "<ol>" : "<ul>");
      }
      listBuf.push(line);
      result.push(line);
    } else {
      if (listBuf !== null) {
        result.push(isOrderedBuf ? "</ol>" : "</ul>");
        listBuf = null;
      }
      result.push(line);
    }
  }
  if (listBuf !== null) {
    result.push(isOrderedBuf ? "</ol>" : "</ul>");
  }
  return result.join("\n");
}
function wrapParagraphs(text) {
  const blocks = text.split(/\n\n+/);
  return blocks.map((block) => {
    const trimmed = block.trim();
    if (!trimmed) return "";
    if (/^<(h[1-6]|hr|pre|ul|ol|blockquote|div|img|table)[\s>]/.test(trimmed)) return block;
    const lines = block.split("\n").filter((l) => l.trim());
    return "\n" + lines.map((l) => {
      if (l.startsWith("<")) return l;
      if (!l.trim()) return "";
      return `<p>${l}</p>`;
    }).join("\n") + "\n";
  }).join("\n\n");
}
function esc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function extractTags(md) {
  const tags = /* @__PURE__ */ new Set();
  const re = /(^|\s)#([\u4e00-\u9fa5A-Za-z0-9_\/]+)/g;
  let m;
  while (m = re.exec(md)) {
    tags.add(m[2]);
  }
  return Array.from(tags);
}
function extractLinks(md) {
  const out = [];
  const wiki = /\[\[([^\]]+)\]\]/g;
  let m;
  while (m = wiki.exec(md)) {
    const target = m[1].split("|")[0].trim();
    out.push({ target, raw: m[0], context: snippet(md, m.index) });
  }
  const mdlink = /\[([^\]]+)\]\(([^)]+)\)/g;
  while (m = mdlink.exec(md)) {
    out.push({ target: m[2].trim(), raw: m[0], context: snippet(md, m.index) });
  }
  return out;
}
function snippet(text, index) {
  const start = Math.max(0, index - 30);
  const end = Math.min(text.length, index + 60);
  return text.substring(start, end).replace(/\n/g, " ").trim();
}

// src/htmlTemplate.ts
function buildMarkdownDoc(renderedHtml) {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0/lxgwwenkai-regular.css">
<style>
  :root {
    --parchment: #f5f4ed;
    --ivory: #faf9f5;
    --warm-sand: #e8e6dc;
    --brand: #1B365D;
    --brand-light: #2D5A8A;
    --near-black: #141413;
    --dark-warm: #3d3d3a;
    --olive: #504e49;
    --stone: #6b6a64;
    --border: #e8e6dc;
    --code-bg: #2D2D2D;
    --blockquote-bg: #f0ede7;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: "LXGW WenKai", "Source Han Serif SC", "Noto Serif CJK SC", "Songti SC", Georgia, serif;
    font-size: 15px; font-weight: 400; line-height: 1.75; letter-spacing: 0.35px;
    color: var(--near-black); background: var(--parchment);
    padding: 40px 56px; max-width: 800px; margin: 0 auto;
    -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  }
  h1, h2, h3, h4, h5, h6 {
    font-family: "LXGW WenKai", "Source Han Serif SC", Georgia, serif;
    font-weight: 500; color: var(--brand); line-height: 1.25; letter-spacing: 0;
  }
  h1 { font-size: 2em; border-bottom: 2px solid var(--border); padding-bottom: 0.35em; margin-top: 0.6em; margin-bottom: 0.6em; color: var(--near-black); }
  h2 { font-size: 1.55em; border-bottom: 1px solid var(--border); padding-bottom: 0.25em; margin-top: 1.6em; margin-bottom: 0.5em; }
  h3 { font-size: 1.25em; margin-top: 1.4em; }
  h4 { font-size: 1.1em; margin-top: 1.2em; }
  h5 { font-size: 1em; color: var(--olive); }
  h6 { font-size: 0.9em; color: var(--stone); }
  p { margin-bottom: 1em; }
  a { color: var(--brand-light); text-decoration: none; border-bottom: 1px solid transparent; transition: border-color 0.18s ease; }
  a:hover { border-bottom-color: var(--brand-light); }
  strong { font-weight: 500; }
  code { font-family: "JetBrains Mono", "Fira Code", "SF Mono", Consolas, monospace; font-size: 0.85em; background: var(--warm-sand); padding: 1px 6px; border-radius: 4px; color: var(--brand); }
  pre { background: var(--code-bg); color: var(--warm-sand); padding: 16px 20px; border-radius: 8px; overflow-x: auto; margin: 1.2em 0; font-size: 13px; line-height: 1.6; }
  pre code { background: none; color: inherit; padding: 0; font-size: inherit; border-radius: 0; }
  blockquote { border-left: 3px solid var(--brand); margin: 1.2em 0; padding: 10px 18px; color: var(--olive); background: var(--blockquote-bg); border-radius: 0 6px 6px 0; }
  blockquote p { margin-bottom: 0; }
  hr { border: none; height: 1px; background: var(--border); margin: 2em 0; }
  ul, ol { padding-left: 1.6em; margin-bottom: 1em; }
  li { margin-bottom: 0.35em; }
  img { max-width: 100%; height: auto; border-radius: 6px; margin: 1em 0; }
  .wikilink { color: var(--brand); background: rgba(27,54,93,0.07); padding: 1px 5px; border-radius: 3px; cursor: pointer; font-weight: 500; }
  @keyframes fadeIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }
  body { animation: fadeIn 0.4s ease-out; }
  .frontmatter { background: var(--ivory); border: 1px solid var(--border); border-radius: 8px; padding: 14px 20px; margin-bottom: 1.5em; display: flex; flex-wrap: wrap; gap: 6px 24px; font-size: 0.88em; }
  .fm-item { display: inline-flex; align-items: baseline; gap: 6px; }
  .fm-plain { color: var(--dark-warm); }
  .fm-key { color: var(--stone); font-weight: 500; min-width: 52px; text-align: right; }
  .fm-val { color: var(--dark-warm); }
  .tag { color: var(--brand-light); background: rgba(45,90,138,0.08); padding: 1px 6px; border-radius: 4px; font-size: 0.9em; white-space: nowrap; }
  h3.section-num { color: var(--near-black); font-size: 1.2em; margin-top: 1.8em; margin-bottom: 0.4em; padding-bottom: 0.15em; border-bottom: 1px solid var(--warm-sand); }
  li.indent-1, li.indent-2, li.indent-3 { list-style-position: outside; }
  ul li.indent-1 { margin-left: 1.2em; }
  ul li.indent-2 { margin-left: 2.4em; color: var(--olive); }
  ul li.indent-3 { margin-left: 3.6em; color: var(--stone); }
  table { width: 100%; border-collapse: collapse; margin: 1.2em 0; font-size: 0.92em; line-height: 1.6; }
  th, td { padding: 0.6em 1em; text-align: left; border-bottom: 1px solid var(--border); vertical-align: top; }
  th { font-weight: 600; color: var(--brand); background: rgba(27, 54, 93, 0.05); border-bottom: 2px solid var(--brand); }
  tr:hover td { background: rgba(27, 54, 93, 0.03); }
  tr:last-child td { border-bottom: none; }
</style>
</head>
<body>${renderedHtml}</body>
</html>`;
}
function buildYamlDoc(yamlText) {
  const lines = yamlText.split("\n");
  const body = lines.map((line) => {
    const escaped = line.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const m = escaped.match(/^(\s*)([^:\s][^:]*?):(.*)$/);
    if (m) {
      const indent = m[1];
      const key = m[2];
      const val = m[3].trim();
      const valHtml = val ? `<span class="y-val">${val}</span>` : "";
      return `${indent}<span class="y-key">${key}</span>:${valHtml}`;
    }
    if (/^\s*#/.test(escaped)) return `<span class="y-comment">${escaped}</span>`;
    if (/^\s*-\s+/.test(escaped)) {
      return escaped.replace(/^(\s*)(-\s+)(.*)$/, '$1<span class="y-dash">$2</span>$3');
    }
    return escaped;
  }).join("\n");
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  :root {
    --parchment: #f5f4ed;
    --ivory: #faf9f5;
    --brand: #1B365D;
    --brand-light: #2D5A8A;
    --warm-sand: #e8e6dc;
    --stone: #6b6a64;
    --olive: #504e49;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: "JetBrains Mono", "SF Mono", Menlo, Consolas, monospace;
    font-size: 13.5px; line-height: 1.7; letter-spacing: 0.2px;
    color: #2b2b2b; background: var(--parchment);
    padding: 40px 56px; max-width: 760px; margin: 0 auto;
    -webkit-font-smoothing: antialiased;
  }
  pre { white-space: pre-wrap; word-break: break-word; }
  .y-key { color: var(--brand); font-weight: 600; }
  .y-val { color: #8a5a2b; }
  .y-comment { color: var(--stone); font-style: italic; }
  .y-dash { color: var(--brand-light); }
  @keyframes fadeIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }
  body { animation: fadeIn 0.4s ease-out; }
</style>
</head>
<body><pre>${body}</pre></body>
</html>`;
}

// src/search.ts
var import_obsidian = require("obsidian");
var InkwellSearchModal = class extends import_obsidian.Modal {
  constructor(app, onChoose, scope) {
    super(app);
    this.query = "";
    this.results = [];
    this.selected = 0;
    this.onChoose = onChoose;
    this.scopeFolder = scope;
    this.allFiles = collectRenderableFiles(app.vault, scope);
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("inkwell-search-modal");
    this.modalEl.setCssProps({ "--ink-search-width": "560px" });
    this.titleEl.hide();
    const wrapper = contentEl.createDiv({ cls: "inkwell-search-input-wrapper" });
    const iconBox = wrapper.createDiv({ cls: "inkwell-search-icon" });
    (0, import_obsidian.setIcon)(iconBox, "search");
    this.inputEl = wrapper.createEl("input", {
      cls: "inkwell-search-input",
      attr: { placeholder: "\u641C\u7D22\u7B14\u8BB0\u2026", autocomplete: "off", spellcheck: "false" }
    });
    const kbd = wrapper.createEl("kbd", { text: "ESC" });
    kbd.addEventListener("click", () => this.close());
    this.listEl = contentEl.createDiv({ cls: "inkwell-search-results" });
    this.inputEl.addEventListener("input", () => {
      this.query = this.inputEl.value;
      this.updateResults();
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Escape") {
        e.preventDefault();
        this.close();
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        this.setSelected(Math.min(this.selected + 1, this.results.length - 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        this.setSelected(Math.max(this.selected - 1, 0));
      } else if (e.key === "Enter") {
        e.preventDefault();
        const file = this.results[this.selected];
        if (file) {
          this.onChoose(file);
          this.close();
        }
      }
    });
    this.updateResults();
    setTimeout(() => this.inputEl.focus(), 20);
  }
  setSelected(i) {
    this.selected = i;
    this.renderList();
    const el = this.listEl.querySelector(`[data-idx="${i}"]`);
    if (el) el.scrollIntoView({ block: "nearest" });
  }
  updateResults() {
    const q = this.query.trim().toLowerCase();
    if (!q) {
      this.results = [];
      this.selected = 0;
      this.renderList();
      return;
    }
    this.results = this.allFiles.filter((f) => f.name.toLowerCase().includes(q) || f.path.toLowerCase().includes(q)).slice(0, 30);
    this.selected = 0;
    this.renderList();
  }
  renderList() {
    this.listEl.empty();
    if (this.results.length === 0) {
      if (this.query.trim()) {
        this.listEl.createDiv({ cls: "inkwell-search-empty", text: "\u672A\u627E\u5230\u76F8\u5173\u7B14\u8BB0" });
      }
      return;
    }
    this.results.forEach((file, i) => {
      const item = this.listEl.createDiv({ cls: "inkwell-search-item", attr: { "data-idx": String(i) } });
      if (i === this.selected) item.addClass("selected");
      const iconWrap = item.createDiv({ cls: "inkwell-search-item-icon" });
      const ext = extOf(file.name);
      iconWrap.addClass(ext === "html" || ext === "htm" ? "html" : ext === "md" || ext === "mdx" ? "md" : "yaml");
      (0, import_obsidian.setIcon)(iconWrap, ext === "html" || ext === "htm" ? "file-code" : ext === "md" || ext === "mdx" ? "file-text" : "braces");
      const info = item.createDiv({ cls: "inkwell-search-item-info" });
      info.createDiv({ cls: "inkwell-search-item-name", text: file.name });
      info.createDiv({ cls: "inkwell-search-item-path", text: file.path });
      item.addEventListener("click", () => {
        this.onChoose(file);
        this.close();
      });
      item.addEventListener("mouseenter", () => this.setSelected(i));
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/InkwellView.ts
var INKWELL_VIEW_TYPE = "inkwell-view";
var InkwellView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    // ---- state ----
    this.rootNodes = [];
    this.childCache = /* @__PURE__ */ new Map();
    this.expanded = /* @__PURE__ */ new Set();
    this.currentFile = null;
    this.mode = "render";
    this.htmlOnly = false;
    this.rightOpen = true;
    this.rightTab = "refs";
    this.siblings = [];
    this.siblingIndex = -1;
    this.sidebarWidth = 240;
    this.resizing = false;
    this.rightTabBtns = {};
    // ---- editing state ----
    this.dirty = false;
    this.sourceArea = null;
    this.badgeEl = null;
    this.autoSaveTimer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return INKWELL_VIEW_TYPE;
  }
  getDisplayText() {
    return "Inkwell";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const s = this.plugin.settings;
    this.htmlOnly = s.htmlOnlyByDefault;
    this.rightOpen = s.rightPanelOpen;
    this.sidebarWidth = s.sidebarWidth;
    this.buildLayout();
    this.bindKeyboard();
    this.bindVaultEvents();
    await this.loadRoot();
  }
  async onClose() {
    await this.flushEdit();
  }
  // ================================================================
  // Layout
  // ================================================================
  buildLayout() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("inkwell");
    contentEl.createDiv({ cls: "inkwell-root" }, (root) => {
      root.createDiv({ cls: "inkwell-topbar" }, (bar) => {
        bar.createDiv({ cls: "inkwell-topbar-title" }, (t) => {
          t.createDiv({ cls: "inkwell-logo-dot" });
          t.createSpan({ text: "Inkwell" });
        });
        bar.createDiv({ cls: "inkwell-topbar-actions" }, (actions) => {
          this.iconBtn(actions, "search", "\u641C\u7D22 (\u2318K)", () => this.openSearch());
          this.iconBtn(actions, this.rightOpen ? "panel-right-close" : "panel-right-open", "\u5207\u6362\u53F3\u4FA7\u9762\u677F", (btn) => {
            this.rightOpen = !this.rightOpen;
            this.rightPanel.toggleClass("hidden", !this.rightOpen);
            (0, import_obsidian2.setIcon)(btn, this.rightOpen ? "panel-right-close" : "panel-right-open");
          });
        });
      });
      root.createDiv({ cls: "inkwell-main" }, (main) => {
        main.createDiv({ cls: "inkwell-sidebar" }, (side) => {
          side.style.setProperty("width", `${this.sidebarWidth}px`);
          side.createDiv({ cls: "inkwell-sidebar-header" }, (header) => {
            const scope = this.plugin.settings.defaultFolder || "Vault";
            header.createSpan({ text: scope.split("/").pop() || scope });
            const btns = header.createDiv({ cls: "inkwell-sidebar-btns" });
            this.filterBtn = this.iconBtn(btns, "filter", this.htmlOnly ? "\u663E\u793A\u5168\u90E8\u6587\u4EF6" : "\u4EC5\u663E\u793A HTML", (btn) => {
              this.htmlOnly = !this.htmlOnly;
              btn.toggleClass("active", this.htmlOnly);
              btn.setAttribute("title", this.htmlOnly ? "\u663E\u793A\u5168\u90E8\u6587\u4EF6" : "\u4EC5\u663E\u793A HTML");
              this.renderTree();
            });
            if (this.htmlOnly) this.filterBtn.addClass("active");
            this.iconBtn(btns, "refresh-cw", "\u5237\u65B0", () => this.refresh());
          });
          this.sidebarTreeEl = side.createDiv({ cls: "inkwell-sidebar-tree" });
        });
        const resizer = main.createDiv({ cls: "inkwell-sidebar-resizer" });
        this.registerDomEvent(resizer, "mousedown", () => this.startResize());
        main.createDiv({ cls: "inkwell-content" }, (content) => {
          content.createDiv({ cls: "inkwell-content-body" }, (body) => {
            this.contentBody = body;
            this.renderEmpty();
          });
          this.bottomBar = content.createDiv({ cls: "inkwell-bottombar hidden" });
          this.buildBottomBar();
        });
        this.rightPanel = main.createDiv({ cls: "inkwell-right-panel" + (this.rightOpen ? "" : " hidden") });
        this.buildRightPanel();
      });
    });
  }
  buildBottomBar() {
    this.bottomBar.createDiv({ cls: "inkwell-bottombar-nav" }, (nav) => {
      const info = nav.createDiv({ cls: "inkwell-doc-nav-info" });
      this.docNavFolder = info.createDiv({ cls: "inkwell-doc-nav-folder" });
      (0, import_obsidian2.setIcon)(this.docNavFolder.createSpan(), "folder");
      this.docNavFolder.createSpan({ cls: "inkwell-doc-nav-folder-name" });
      this.docNavPosition = info.createDiv({ cls: "inkwell-doc-nav-position", text: "" });
      const controls = nav.createDiv({ cls: "inkwell-doc-nav-controls" });
      this.prevBtn = controls.createEl("button", { cls: "inkwell-doc-nav-btn" });
      (0, import_obsidian2.setIcon)(this.prevBtn.createSpan(), "arrow-left");
      this.prevBtn.createSpan({ text: "\u4E0A\u4E00\u7BC7" });
      this.prevBtn.createEl("kbd", { text: "K" });
      this.prevBtn.addEventListener("click", () => this.navigateDoc(-1));
      this.nextBtn = controls.createEl("button", { cls: "inkwell-doc-nav-btn" });
      this.nextBtn.createSpan({ text: "\u4E0B\u4E00\u7BC7" });
      (0, import_obsidian2.setIcon)(this.nextBtn.createSpan(), "arrow-right");
      this.nextBtn.createEl("kbd", { text: "J" });
      this.nextBtn.addEventListener("click", () => this.navigateDoc(1));
    });
    this.bottomBar.createDiv({ cls: "inkwell-bottombar-sep" });
    this.bottomBar.createDiv({ cls: "inkwell-bottombar-views" }, (views) => {
      this.renderBtn = views.createEl("button", { cls: "inkwell-view-btn active", text: "\u6E32\u67D3" });
      this.renderBtn.addEventListener("click", () => this.setMode("render"));
      this.sourceBtn = views.createEl("button", { cls: "inkwell-view-btn", text: "\u6E90\u7801" });
      this.sourceBtn.addEventListener("click", () => this.setMode("source"));
    });
  }
  buildRightPanel() {
    this.rightPanel.createDiv({ cls: "inkwell-panel-header" }, (header) => {
      header.createSpan({ text: "\u53CD\u94FE & \u6807\u7B7E" });
      this.iconBtn(header, "panel-right-close", "\u5173\u95ED\u9762\u677F", (btn) => {
        this.rightOpen = false;
        this.rightPanel.addClass("hidden");
        (0, import_obsidian2.setIcon)(btn, "panel-right-close");
        const topToggle = this.contentEl.querySelector(".inkwell-topbar-actions button:nth-child(2)");
        if (topToggle) (0, import_obsidian2.setIcon)(topToggle, "panel-right-open");
      });
    });
    const tabs = this.rightPanel.createDiv({ cls: "inkwell-panel-tabs" });
    for (const [key, label] of [["refs", "\u5F15\u7528"], ["out", "\u51FA\u94FE"], ["tags", "\u6807\u7B7E"]]) {
      const btn = tabs.createEl("button", { cls: "inkwell-panel-tab" + (key === this.rightTab ? " active" : ""), text: label });
      btn.addEventListener("click", () => {
        this.rightTab = key;
        for (const k of Object.keys(this.rightTabBtns)) {
          this.rightTabBtns[k].toggleClass("active", k === key);
        }
        this.renderRightPanel();
      });
      this.rightTabBtns[key] = btn;
    }
    this.rightContent = this.rightPanel.createDiv({ cls: "inkwell-panel-content" });
    this.renderRightPanelPlaceholder();
  }
  // ================================================================
  // Tree
  // ================================================================
  async loadRoot() {
    const scope = this.plugin.settings.defaultFolder;
    try {
      this.rootNodes = await listDirectory(this.app.vault.adapter, scope);
      this.renderTree();
    } catch (e) {
      this.sidebarTreeEl.empty();
      this.sidebarTreeEl.createDiv({ cls: "inkwell-tree-error", text: `\u52A0\u8F7D\u5931\u8D25: ${String(e)}` });
    }
  }
  renderTree() {
    this.sidebarTreeEl.empty();
    if (this.rootNodes.length === 0) {
      this.sidebarTreeEl.createDiv({ cls: "inkwell-tree-empty", text: "\u6CA1\u6709\u53EF\u6E32\u67D3\u7684\u6587\u4EF6" });
      return;
    }
    this.renderNodes(this.rootNodes, 0, this.sidebarTreeEl);
  }
  renderNodes(nodes, depth, container) {
    const visible = this.htmlOnly ? nodes.filter((n) => n.isDir || n.ext === "html" || n.ext === "htm") : nodes;
    for (const node of visible) {
      const indent = depth * 16;
      if (node.isDir) {
        const isExpanded = this.expanded.has(node.path);
        const row = container.createDiv({ cls: "inkwell-tree-node folder" });
        row.style.setProperty("padding-left", `calc(var(--iw-space-2) + ${indent}px)`);
        const arrow = row.createSpan({ cls: "inkwell-tree-arrow" + (isExpanded ? " expanded" : "") });
        (0, import_obsidian2.setIcon)(arrow, "chevron-right");
        const icon = row.createSpan({ cls: "inkwell-tree-icon folder" });
        (0, import_obsidian2.setIcon)(icon, isExpanded ? "folder-open" : "folder");
        row.createSpan({ cls: "inkwell-tree-name", text: node.name });
        row.addEventListener("click", () => this.toggleFolder(node));
        if (isExpanded) {
          const children = this.childCache.get(node.path) ?? node.children ?? [];
          if (children.length > 0) {
            this.renderNodes(children, depth + 1, container);
          }
        }
      } else {
        const ext = node.ext || "";
        const isHtml = ext === "html" || ext === "htm";
        const isMd = ext === "md" || ext === "mdx";
        const isYaml = ext === "yaml" || ext === "yml";
        const row = container.createDiv({ cls: "inkwell-tree-node file" + (this.currentFile?.path === node.path ? " active" : "") });
        row.style.setProperty("padding-left", `calc(var(--iw-space-2) + ${indent}px + var(--iw-tree-indent))`);
        row.createSpan({ cls: "inkwell-tree-arrow-spacer" });
        const icon = row.createSpan({ cls: "inkwell-tree-icon " + (isHtml ? "html" : isMd ? "md" : isYaml ? "yaml" : "other") });
        (0, import_obsidian2.setIcon)(icon, isHtml ? "file-code" : isMd ? "file-text" : isYaml ? "braces" : "file");
        row.createSpan({ cls: "inkwell-tree-name", text: node.name });
        row.addEventListener("click", () => this.openFile(node));
      }
    }
  }
  async toggleFolder(node) {
    if (this.expanded.has(node.path)) {
      this.expanded.delete(node.path);
    } else {
      this.expanded.add(node.path);
      if (!this.childCache.has(node.path)) {
        try {
          const children = await listDirectory(this.app.vault.adapter, node.path);
          this.childCache.set(node.path, children);
        } catch {
          this.childCache.set(node.path, []);
        }
      }
    }
    this.renderTree();
  }
  // ================================================================
  // File open / render
  // ================================================================
  async openFile(node) {
    await this.flushEdit();
    const path = node.path;
    const name = node.name;
    const ext = extOf(name);
    try {
      const content = await readFileContent(this.app.vault.adapter, path);
      const fileType = classifyFile(ext);
      const open = {
        path,
        name,
        ext,
        content,
        folder: folderOf(path),
        fileType
      };
      this.currentFile = open;
      this.mode = "render";
      this.updateModeButtons();
      this.renderContent();
      this.updateBottomBar();
      await this.computeSiblings(path);
      this.renderTree();
      this.renderRightPanel();
    } catch (e) {
      new import_obsidian2.Notice(`\u65E0\u6CD5\u6253\u5F00 ${name}: ${String(e)}`);
    }
  }
  renderContent() {
    this.contentBody.empty();
    if (!this.currentFile) {
      this.renderEmpty();
      return;
    }
    const file = this.currentFile;
    this.metaBar = this.contentBody.createDiv({ cls: "inkwell-render-meta" });
    const info = this.metaBar.createDiv({ cls: "inkwell-render-meta-info" });
    const iconWrap = info.createDiv({ cls: "inkwell-render-meta-icon" });
    const ext = file.ext;
    if (ext === "html" || ext === "htm") {
      iconWrap.addClass("html");
      (0, import_obsidian2.setIcon)(iconWrap, "file-code");
    } else if (ext === "md" || ext === "mdx") {
      iconWrap.addClass("md");
      (0, import_obsidian2.setIcon)(iconWrap, "file-text");
    } else if (ext === "yaml" || ext === "yml") {
      iconWrap.addClass("yaml");
      (0, import_obsidian2.setIcon)(iconWrap, "braces");
    } else {
      (0, import_obsidian2.setIcon)(iconWrap, "file");
    }
    info.createSpan({ cls: "inkwell-render-filename", text: file.name });
    this.badgeEl = info.createDiv({ cls: "inkwell-render-badge" });
    this.updateBadge();
    const metaActions = this.metaBar.createDiv({ cls: "inkwell-render-meta-actions" });
    this.saveBtn = this.iconBtn(metaActions, "save", "\u4FDD\u5B58 (\u2318S)", () => this.saveCurrentFile());
    this.saveBtn.disabled = true;
    this.renderScroll = this.contentBody.createDiv({ cls: "inkwell-render-scroll" });
    if (this.mode === "source") {
      const ta = this.renderScroll.createEl("textarea", { cls: "inkwell-source-area" });
      ta.value = file.content;
      ta.setAttribute("spellcheck", "false");
      this.sourceArea = ta;
      ta.addEventListener("input", () => this.onSourceInput());
      setTimeout(() => ta.focus(), 30);
      return;
    }
    this.sourceArea = null;
    let srcDoc = "";
    if (file.fileType === "html") {
      srcDoc = file.content;
    } else if (file.fileType === "md") {
      srcDoc = buildMarkdownDoc(renderMarkdown(file.content));
    } else if (file.fileType === "yaml") {
      srcDoc = buildYamlDoc(file.content);
    } else {
      srcDoc = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:monospace;white-space:pre-wrap;padding:24px;color:#333;background:#fff}</style></head><body>${escapeHtml(file.content)}</body></html>`;
    }
    const iframe = this.renderScroll.createEl("iframe", { cls: "inkwell-render-iframe" });
    iframe.setAttribute("title", file.name);
    const sandbox = this.sandboxAttr();
    if (sandbox !== null) iframe.setAttribute("sandbox", sandbox);
    iframe.setAttribute("srcdoc", srcDoc);
  }
  sandboxAttr() {
    switch (this.plugin.settings.sandboxMode) {
      case "full":
        return "allow-scripts allow-same-origin";
      case "scripts":
        return "allow-scripts";
      case "none":
        return "";
      default:
        return "allow-scripts allow-same-origin";
    }
  }
  renderEmpty() {
    this.contentBody.empty();
    this.contentBody.createDiv({ cls: "inkwell-empty" }, (empty) => {
      const icon = empty.createDiv({ cls: "inkwell-empty-icon" });
      (0, import_obsidian2.setIcon)(icon, "file-code");
      empty.createDiv({ cls: "inkwell-empty-title", text: "\u5F00\u59CB\u4F60\u7684\u7B14\u8BB0\u4E4B\u65C5" });
      empty.createDiv({ cls: "inkwell-empty-desc" }, (d) => {
        d.appendText("\u4ECE\u5DE6\u4FA7\u9009\u62E9\u4E00\u4E2A HTML / Markdown / YAML \u6587\u4EF6\uFF0C\u6216\u6309 ");
        const kbd = d.createEl("kbd", { text: "\u2318K" });
        d.appendText(" \u641C\u7D22");
      });
    });
  }
  async setMode(mode) {
    if (!this.currentFile) return;
    await this.flushEdit();
    this.mode = mode;
    this.updateModeButtons();
    this.renderContent();
  }
  updateModeButtons() {
    this.renderBtn.toggleClass("active", this.mode === "render");
    this.sourceBtn.toggleClass("active", this.mode === "source");
  }
  // ================================================================
  // Editing
  // ================================================================
  onSourceInput() {
    if (!this.sourceArea || !this.currentFile) return;
    this.currentFile.content = this.sourceArea.value;
    this.dirty = true;
    this.updateBadge();
    if (this.saveBtn) this.saveBtn.disabled = false;
    if (this.plugin.settings.autoSave) {
      this.scheduleAutoSave();
    }
  }
  scheduleAutoSave() {
    if (this.autoSaveTimer) clearTimeout(this.autoSaveTimer);
    this.autoSaveTimer = setTimeout(() => void this.saveCurrentFile(), this.plugin.settings.autoSaveDelay);
  }
  updateBadge() {
    if (!this.badgeEl) return;
    if (this.mode === "source") {
      this.badgeEl.setText(this.dirty ? "\u672A\u4FDD\u5B58" : "\u5DF2\u4FDD\u5B58");
      this.badgeEl.toggleClass("dirty", this.dirty);
      this.badgeEl.toggleClass("saved", !this.dirty);
    } else {
      this.badgeEl.setText(this.currentFile?.fileType === "html" ? "\u672C\u5730\u4FE1\u4EFB" : "\u6E32\u67D3\u9884\u89C8");
      this.badgeEl.removeClass("dirty");
      this.badgeEl.removeClass("saved");
    }
  }
  async saveCurrentFile() {
    if (!this.currentFile || !this.dirty) return;
    if (this.sourceArea) this.currentFile.content = this.sourceArea.value;
    try {
      await this.app.vault.adapter.write(this.currentFile.path, this.currentFile.content);
      this.dirty = false;
      if (this.autoSaveTimer) {
        clearTimeout(this.autoSaveTimer);
        this.autoSaveTimer = null;
      }
      this.updateBadge();
      if (this.saveBtn) this.saveBtn.disabled = true;
      new import_obsidian2.Notice(`\u5DF2\u4FDD\u5B58 ${this.currentFile.name}`, 1500);
      this.renderRightPanel();
    } catch (e) {
      new import_obsidian2.Notice(`\u4FDD\u5B58\u5931\u8D25: ${String(e)}`);
    }
  }
  async flushEdit() {
    if (this.mode === "source" && this.sourceArea && this.currentFile) {
      this.currentFile.content = this.sourceArea.value;
    }
    if (this.dirty) {
      await this.saveCurrentFile();
    }
  }
  // ================================================================
  // Navigation
  // ================================================================
  async computeSiblings(currentPath) {
    const parent = currentPath.includes("/") ? currentPath.substring(0, currentPath.lastIndexOf("/")) : "";
    try {
      const nodes = await listDirectory(this.app.vault.adapter, parent);
      this.siblings = nodes.filter((n) => !n.isDir && RENDERABLE_EXTS.has(n.ext || ""));
      this.siblingIndex = this.siblings.findIndex((f) => f.path === currentPath);
    } catch {
      this.siblings = [];
      this.siblingIndex = -1;
    }
    this.updateBottomBar();
  }
  navigateDoc(direction) {
    const next = this.siblingIndex + direction;
    if (next < 0 || next >= this.siblings.length) return;
    const node = this.siblings[next];
    void this.openFile(node);
  }
  updateBottomBar() {
    if (!this.currentFile) {
      this.bottomBar.addClass("hidden");
      return;
    }
    this.bottomBar.removeClass("hidden");
    const folderNameEl = this.docNavFolder.querySelector(".inkwell-doc-nav-folder-name");
    if (folderNameEl) folderNameEl.setText(this.currentFile.folder || "(root)");
    this.docNavPosition.setText(
      this.siblingIndex >= 0 ? `${this.siblingIndex + 1} / ${this.siblings.length}` : ""
    );
    this.prevBtn.disabled = this.siblingIndex <= 0;
    this.nextBtn.disabled = this.siblingIndex >= this.siblings.length - 1;
  }
  // ================================================================
  // Right panel
  // ================================================================
  renderRightPanelPlaceholder() {
    this.rightContent.empty();
    if (!this.currentFile) {
      this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u6253\u5F00\u6587\u4EF6\u540E\u67E5\u770B\u5F15\u7528\u5173\u7CFB" });
    } else {
      this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u52A0\u8F7D\u4E2D\u2026" });
    }
  }
  async renderRightPanel() {
    if (!this.currentFile) {
      this.renderRightPanelPlaceholder();
      return;
    }
    this.rightContent.empty();
    if (this.rightTab === "tags") {
      const tags = extractTags(this.currentFile.content);
      if (tags.length === 0) {
        this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u5F53\u524D\u6587\u4EF6\u6CA1\u6709\u6807\u7B7E" });
        return;
      }
      const wrap = this.rightContent.createDiv({ cls: "inkwell-tag-cloud" });
      for (const tag of tags) {
        wrap.createEl("span", { cls: "inkwell-tag-chip", text: `#${tag}` });
      }
      return;
    }
    if (this.rightTab === "out") {
      const links = extractLinks(this.currentFile.content);
      if (links.length === 0) {
        this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u5F53\u524D\u6587\u4EF6\u6CA1\u6709\u51FA\u94FE" });
        return;
      }
      for (const link of links) {
        const card = this.rightContent.createDiv({ cls: "inkwell-backlink-card" });
        card.createDiv({ cls: "inkwell-backlink-name", text: link.target });
        card.createDiv({ cls: "inkwell-backlink-context", text: link.context });
        card.addEventListener("click", () => this.openByName(link.target));
      }
      return;
    }
    this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u641C\u7D22\u5F15\u7528\u4E2D\u2026" });
    try {
      const refs = await findReferences(
        this.app,
        { name: this.currentFile.name, path: this.currentFile.path },
        this.plugin.settings.defaultFolder || void 0
      );
      this.rightContent.empty();
      if (refs.length === 0) {
        this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u6CA1\u6709\u5176\u4ED6\u6587\u4EF6\u5F15\u7528\u6B64\u6587\u4EF6" });
        return;
      }
      for (const ref of refs) {
        const card = this.rightContent.createDiv({ cls: "inkwell-backlink-card" });
        card.createDiv({ cls: "inkwell-backlink-name", text: ref.name });
        card.createDiv({ cls: "inkwell-backlink-context", text: ref.context });
        card.createDiv({ cls: "inkwell-backlink-path", text: ref.path });
        card.addEventListener("click", () => this.openByPath(ref.path));
      }
    } catch {
      this.rightContent.empty();
      this.rightContent.createDiv({ cls: "inkwell-panel-hint", text: "\u5F15\u7528\u641C\u7D22\u5931\u8D25" });
    }
  }
  async openByName(name) {
    const cleaned = name.replace(/\.[^.]+$/, "");
    const file = this.app.vault.getFiles().find((f) => {
      const base = f.name.replace(/\.[^.]+$/, "");
      return base === cleaned || f.name === name;
    });
    if (file) {
      await this.openFile(file);
    } else {
      new import_obsidian2.Notice(`\u672A\u627E\u5230\u6587\u4EF6: ${name}`);
    }
  }
  async openByPath(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian2.TFile) {
      await this.openFile(file);
    } else {
      new import_obsidian2.Notice(`\u672A\u627E\u5230\u6587\u4EF6: ${path}`);
    }
  }
  // ================================================================
  // Search / refresh / resize
  // ================================================================
  openSearch() {
    new InkwellSearchModal(
      this.app,
      (file) => void this.openFile(file),
      this.plugin.settings.defaultFolder || void 0
    ).open();
  }
  async refresh() {
    this.childCache.clear();
    this.expanded.clear();
    await this.loadRoot();
    if (this.currentFile) {
      try {
        const content = await readFileContent(this.app.vault.adapter, this.currentFile.path);
        this.currentFile.content = content;
        this.renderContent();
        this.renderRightPanel();
      } catch {
      }
    }
  }
  bindVaultEvents() {
    const debounced = (0, import_obsidian2.debounce)(() => void this.refresh(), this.plugin.settings.refreshDebounce, true);
    this.registerEvent(this.app.vault.on("create", debounced));
    this.registerEvent(this.app.vault.on("delete", debounced));
    this.registerEvent(this.app.vault.on("rename", debounced));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (this.currentFile && file.path === this.currentFile.path) {
        void this.refresh();
      } else {
        debounced();
      }
    }));
  }
  bindKeyboard() {
    this.registerDomEvent(this.contentEl, "keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && (e.key === "s" || e.key === "S")) {
        e.preventDefault();
        void this.saveCurrentFile();
        return;
      }
      const target = e.target;
      const typing = target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement;
      if (typing) return;
      if (e.key === "j" || e.key === "J") {
        e.preventDefault();
        this.navigateDoc(1);
      } else if (e.key === "k" || e.key === "K") {
        e.preventDefault();
        this.navigateDoc(-1);
      }
    });
  }
  startResize() {
    this.resizing = true;
    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";
    const onMove = (e) => {
      if (!this.resizing) return;
      const rect = this.contentEl.getBoundingClientRect();
      const newWidth = Math.max(160, Math.min(480, e.clientX - rect.left));
      this.sidebarWidth = newWidth;
      const side = this.contentEl.querySelector(".inkwell-sidebar");
      if (side) side.style.setProperty("width", `${newWidth}px`);
    };
    const onUp = () => {
      this.resizing = false;
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseup", onUp);
      this.plugin.settings.sidebarWidth = this.sidebarWidth;
      void this.plugin.saveSettings();
    };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
  }
  // ================================================================
  // Helpers
  // ================================================================
  iconBtn(parent, icon, title, onClick) {
    const btn = parent.createEl("button", { cls: "inkwell-view-btn", attr: { title } });
    (0, import_obsidian2.setIcon)(btn, icon);
    btn.addEventListener("click", () => onClick(btn));
    return btn;
  }
};
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultFolder: "",
  rightPanelOpen: true,
  htmlOnlyByDefault: false,
  sandboxMode: "full",
  refreshDebounce: 1e3,
  sidebarWidth: 240,
  autoSave: true,
  autoSaveDelay: 800
};
var InkwellSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "Inkwell" });
    containerEl.createEl("p", {
      cls: "setting-item-description",
      text: "A native HTML / Markdown / YAML reader inside Obsidian."
    });
    new import_obsidian3.Setting(containerEl).setName("Default folder").setDesc("Vault-relative folder to scope the file tree on open (empty = whole vault).").addText(
      (text) => text.setPlaceholder("e.g. Notes").setValue(this.plugin.settings.defaultFolder).onChange(async (value) => {
        this.plugin.settings.defaultFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Open references panel on launch").setDesc("Show the backlinks / outlinks / tags panel by default.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.rightPanelOpen).onChange(async (value) => {
        this.plugin.settings.rightPanelOpen = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("HTML-only filter by default").setDesc("Hide non-HTML files in the tree when the view opens.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.htmlOnlyByDefault).onChange(async (value) => {
        this.plugin.settings.htmlOnlyByDefault = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("HTML sandbox mode").setDesc(
      '"full" = scripts + same-origin (matches desktop app, enables charts/interactivity). "scripts" = no same-origin. "none" = fully locked (static HTML only).'
    ).addDropdown(
      (dropdown) => dropdown.addOption("full", "Full (scripts + same-origin)").addOption("scripts", "Scripts only").addOption("none", "None (static)").setValue(this.plugin.settings.sandboxMode).onChange(async (value) => {
        this.plugin.settings.sandboxMode = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Auto-refresh debounce (ms)").setDesc("How long to wait after a vault change before refreshing the tree.").addText(
      (text) => text.setPlaceholder("1000").setValue(String(this.plugin.settings.refreshDebounce)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n >= 100) {
          this.plugin.settings.refreshDebounce = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Sidebar width (px)").setDesc("Default width of the file tree sidebar.").addText(
      (text) => text.setPlaceholder("240").setValue(String(this.plugin.settings.sidebarWidth)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n >= 160 && n <= 480) {
          this.plugin.settings.sidebarWidth = n;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Auto-save while editing").setDesc("Automatically write edits back to the vault after you stop typing.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSave).onChange(async (value) => {
        this.plugin.settings.autoSave = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Auto-save delay (ms)").setDesc("How long to wait after the last keystroke before saving.").addText(
      (text) => text.setPlaceholder("800").setValue(String(this.plugin.settings.autoSaveDelay)).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n >= 200 && n <= 5e3) {
          this.plugin.settings.autoSaveDelay = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/main.ts
var InkwellPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    (0, import_obsidian4.addIcon)(
      "inkwell",
      `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M20.24 12.24a6 6 0 0 0-8.49-8.49L5 10.5V19h8.5z"/><path d="M16 8 2 22"/><path d="M17.5 15H9"/></svg>`
    );
    this.registerView(INKWELL_VIEW_TYPE, (leaf) => new InkwellView(leaf, this));
    this.addRibbonIcon("inkwell", "Open Inkwell", () => {
      void this.activateView();
    });
    this.addStatusBarItem().setText("Inkwell ready");
    this.addCommand({
      id: "open-inkwell",
      name: "Open Inkwell reader",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "inkwell-search",
      name: "Search files in Inkwell",
      hotkeys: [{ modifiers: ["Mod"], key: "k" }],
      callback: () => {
        const view = this.getActiveView();
        if (view) {
          view.openSearch();
        } else {
          void this.activateView().then(() => {
            setTimeout(() => this.getActiveView()?.openSearch(), 120);
          });
        }
      }
    });
    this.addCommand({
      id: "open-current-in-inkwell",
      name: "Open current file in Inkwell",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file) return false;
        if (!RENDERABLE_EXTS.has(extOf(file.name))) return false;
        if (checking) return true;
        void this.activateView().then(() => {
          const view = this.getActiveView();
          if (view) void view.openFile(file);
        });
        return true;
      }
    });
    this.addCommand({
      id: "save-current-in-inkwell",
      name: "Save current file (Inkwell)",
      hotkeys: [{ modifiers: ["Mod"], key: "s" }],
      checkCallback: (checking) => {
        const view = this.getActiveView();
        if (!view) return false;
        if (checking) return true;
        void view.saveCurrentFile();
        return true;
      }
    });
    this.addSettingTab(new InkwellSettingTab(this.app, this));
  }
  async onunload() {
  }
  async activateView(file) {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(INKWELL_VIEW_TYPE);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({ type: INKWELL_VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
    if (file) {
      const view = leaf.view;
      if (view instanceof InkwellView) {
        await view.openFile(file);
      }
    }
  }
  getActiveView() {
    const leaves = this.app.workspace.getLeavesOfType(INKWELL_VIEW_TYPE);
    if (leaves.length === 0) return null;
    const view = leaves[0].view;
    return view instanceof InkwellView ? view : null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
